# Common Labels
labels:
  app: "hearing-scheduled-completed-cron"
  group: "cronjobs"

# Cron schedule
cron:
  schedule: "0 18 * * *"
  timezone: "Asia/Kolkata"

# Container Configs
image:
  repository: "docker.io/venkatramireddyb/cronjob"
  tag: "v1"

# Environment variables sourced from ConfigMap
env: |
  - name: HEARING_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: hearing

command:
  - "bin/sh"
  - "-c"
  - |
    curl -X POST --location "${HEARING_HOST}hearing/v1/_runCronJob"