apiVersion: v1
kind: ServiceAccount
metadata:
  name: egov-developer-sa
  namespace: egov
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: egov-developer-role
  namespace: egov
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - ''
      - apps
      - networking.k8s.io
    resources:
      - deployments
      - deployments/rollback
      - deployments/scale
      - deployments/status
      - ingresses
      - services
      - replicasets
      - pods
      - pods/log
      - pods/portforward
      - configmaps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: egov-developer-rb
  namespace: egov
subjects:
- kind: ServiceAccount
  name: egov-developer-sa
  namespace: egov
roleRef:
  kind: Role
  name: egov-developer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backbone-pod-lister
  namespace: backbone
rules:
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
      - create
    apiGroups:
      - ''
      - apps
      - networking.k8s.io
    resources:
      - pods/portforward
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backbone-pod-lister-rb
  namespace: backbone
subjects:
- kind: ServiceAccount
  name: egov-developer-sa
  namespace: egov
roleRef:
  kind: Role
  name: backbone-pod-lister
  apiGroup: rbac.authorization.k8s.io
