apiVersion: v1
kind: Secret
metadata:
  name: egov-developer-token
  namespace: egov
  annotations:
    kubernetes.io/service-account.name: egov-developer-sa
type: kubernetes.io/service-account-token
