{{- define "common.ingress" -}}
{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: {{ template "common.name" . }}
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- else if .Values.ingress.namespace }}
  namespace: {{ .Values.ingress.namespace }}    
{{- else }}  
  namespace: {{ .Values.namespace }}  
{{- end }}     
  annotations:
{{- toYaml .Values.ingress.annotations | nindent 4 }}   
{{- if .Values.ingress.waf.enabled }}      
{{- toYaml .Values.ingress.waf.annotations | nindent 4 }} 
{{- end  }}
{{- if .Values.ingress.nginxRateLimit.enabled }}
    nginx.ingress.kubernetes.io/limit-rpm: "{{ .Values.ingress.nginxRateLimit.rpm }}"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "{{ .Values.ingress.nginxRateLimit.burstMultiplier }}"
    nginx.ingress.kubernetes.io/limit-connections: "{{ .Values.ingress.nginxRateLimit.connections }}"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Xss-Protection: 1; mode=block";
      limit_req_status 429;
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
      more_set_headers "Content-Security-Policy: object-src "self"; media-src "self"; frame-ancestors "none"; base-uri "self"; frame-src "self"; worker-src "self"; manifest-src "self";" always;
{{- end }}
{{- if .Values.ingress.additionalAnnotations }}                                   
  {{- tpl  .Values.ingress.additionalAnnotations . | nindent 4 }}
{{- end }} 
  labels:
{{- include "common.labels" . | nindent 4 }}                            
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
{{- if .Values.ingress.host }}   
  {{- tpl  .Values.ingress.host . | nindent 2 }}
{{- else if .Values.ingress.hostName }} 
  - host: {{ .Values.ingress.hostName }}
{{- else }}  
  - host: {{ .Values.global.domain }}
{{- end }}  
    http:
      paths:
      - backend:
{{- if .Values.ingress.zuul }}          
          service:
            name: gateway
            port:
              number: 8080
{{ else }}
          service:
            name: {{ .Values.ingress.serviceName | default (include "common.name" .) }}
            port:
              number: {{ .Values.ingress.servicePort | default .Values.httpPort }}
{{- end }}            
        path: /{{ .Values.ingress.context }}
        pathType: Prefix
{{- if ne .Values.global.setup "quickstart" }}        
  tls:
{{- if .Values.ingress.tls }}
  {{- tpl  .Values.ingress.tls . | nindent 2 }}
{{- else }} 
{{- if .Values.ingress.hostName }}
  - hosts: 
    - {{ .Values.ingress.hostName }}
    secretName: {{ .Values.ingress.hostName }}-tls-certs  
{{- else }}      
  - hosts:
    - {{ .Values.global.domain }}
    secretName: {{ .Values.global.domain }}-tls-certs 
{{- end }} 
{{- end }} 
{{- end }}
{{- end -}} 
{{- end -}} 