# Common Labels
labels:
  app: "ordermanagement-mandatory-submission"
  group: "cronjobs"

# Cron schedule
cron:
  schedule: "0 18 * * *"
  timezone: "Asia/Kolkata"

# Container Configs

image:
  repository: "docker.io/venkatramireddyb/cronjob"
  tag: "v1"

# Environment variables sourced from ConfigMap
env: |
  - name: ORDER_MANAGEMENT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: order-management

command:
  - "bin/sh"
  - "-c"
  - |
    curl -X POST --location "${ORDER_MANAGEMENT_HOST}order-management/v1/_runCronJob"