apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backbone-stg-acme-challenge
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - service: acme-challenge
  template:
    metadata:
      name: "staging-{{service}}"
    spec:
      project: oncourts-project
      sources:
        - repoURL: https://github.com/pucardotorg/pucar-DevOps.git
          targetRevision: pucar-stg
          path: "deploy-as-code/charts/backbone-services/{{service}}"
          helm:
            valueFiles:
              - values.yaml
              - ../../environments/pucar-stg.yaml
              - ../../environments/pucar-stg-config.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: backbone-stg
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 100
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
