{{- $_ := include "acme-challenge.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: acme-nginx-config
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
        listen {{ .Values.nginx.containerPort }};
        server_name _;

        location /.well-known/acme-challenge/ {
            root /usr/share/nginx/html;
        }

        location / {
            return 404;
        }
    }
