apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-challenge.name" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "acme-challenge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.nginx.containerPort }}
      protocol: TCP
  selector:
    {{- include "acme-challenge.labels" . | nindent 4 }}
