configmaps:
  egov-config:
    name: egov-config
    namespace: egov
    data:
      COURT_ADDRESS: 'Special Court of Judicial Magistrate of the First Class, for the trial of cases under section 138 of Negotiable Instruments Act, 1881 (''24x7 ON COURT''), Kollam, Kerala, 691013'
      db-url: 'jdbc:postgresql://10.5.94.176:5432/prod'
      server-tomcat-max-threads: '10'
      judge-designation: Judicial Magistrate of the First Class
      judge-name: Michael George
      egov-services: 'https://oncourts.kerala.gov.in'
      domain: oncourts.kerala.gov.in
      spring-datasource-tomcat-initialSize: '1'
      dristi-e-sign: 'https://oncourts.kerala.gov.in/digit-ui/'
      esign-id: KRHC-001
      s3-assets-bucket: (pg-egov-assets|egov-playground-assets)
      mobile-validation-workaround: 'true'
      es-host: elasticsearch-data.backbone-prod
      etreasury: 'http://etreasury.pucar-prod:8080'
      egov-bnd-freedownload-tenants: pg.testing
      serializers-timezone-in-ist: 'true'
      flyway-locations: 'filesystem:/flyway/sql,filesystem:/flyway/seed,filesystem:/flyway/qa'
      tracer-errors-provideexceptionindetails: 'true'
      server-tomcat-max-connections: '500'
      sms-enabled: 'true'
      esign-filestore-id: 2aefb901-edc6-4a45-95f8-3ea383a513f5
      dristi-url: 'https://oncourts.kerala.gov.in/user/oauth/token?_=1713357247536'
      spring-jpa-show-sql: 'true'
      spring-datasource-tomcat-max-active: '2'
      sbi-tranction-success-url: 'https://oncourts.kerala.gov.in/sbi-payment/success.jsp'
      ORDER_HEADING: 'Before The Special Court Of Judicial Magistrate of the First Class , for the trial of cases under section 138 of NI Act , 1881 at Kollam ( "24X7 ON Court" )'
      sbi-redirect-url: 'https://oncourts.kerala.gov.in/digit-ui/citizen/home/sbi-payment-screen'
      logging-level-jdbc: DEBUG
      kafka-brokers: 'kafka-kraft-controller-headless.backbone-prod:9092'
      sbi-tranction-fail-url: 'https://oncourts.kerala.gov.in/sbi-payment/fail.jsp'
      egov-state-level-tenant-id: kl
      es-indexer-host: 'http://elasticsearch-data.backbone-prod:9200/'
      kafka-infra-brokers: 'kafka-v2-infra.kafka-cluster:9092'
      db-host: 10.5.94.176
      egov-services-fqdn-name: 'https://oncourts.kerala.gov.in/'
      timezone: Asia/Kolkata
      esign-interceptor: 'https://oncourts.kerala.gov.in/esign-interceptor/v1/_intercept'
      db-name: prod
      sbi-tranction-url: 'https://test.sbiepay.sbi/secure/AggregatorHostedListener'
      egov-bnd-live-citizen-tenants: pg.testing
      JUDGE_DESIGNATION_HEADER: 'Special Court Of Judicial Magistrate of the First Class , for the trial of cases under section 138 of NI Act , 1881 at Kollam ( "24X7 ON Court" )'
      service-dept-code: 01BRAA
      COURT_NAME: 'Special Court Of Judicial Magistrate of the First Class , for the trial of cases under section 138 of NI Act , 1881 at Kollam ( "24X7 ON Court" )'
      service-name: 'icops'
      service-ky: IC0001
      auth-type: get_auth_token
      domain-url: https://demo.pucar.org

  egov-service-host:
    name: egov-service-host
    namespace: egov

root-ingress:
  name: root-ingress
  namespace: egov
  cert-issuer: "letsencrypt-prod"
  serviceName: oncourts-website
  servicePort: 3000
secrets:
  db:
    name: db
    namespace: egov
  git-sync:
    name: git-creds
    namespace: egov
  egov-filestore:
    name: egov-filestore
    namespace: egov
  egov-location:
    name: egov-location
    namespace: egov
  egov-enc-service:
    name: egov-enc-service
    namespace: egov
  egov-notification-sms:
    name: egov-notification-sms
    namespace: egov
  egov-notification-mail:
    name: egov-notification-mail
    namespace: egov
  oauth2-proxy:
    name: oauth2-proxy
    namespace: egov
  elasticsearch:
    name: elasticsearch-credentials
    namespace: egov
  egov-pg-service:
    name: egov-pg-service
    namespace: egov
