# Common Labels
labels:
  app: "etreasury-process-reconciliation"
  group: "cronjobs"

# Cron schedule
cron:
  schedule: "*/30 * * * *"
  timezone: "Asia/Kolkata"


# Container Configs
image:
  repository: "docker.io/venkatramireddyb/cronjob"
  tag: "v1"

# Environment variables sourced from ConfigMap
env: |
  - name: ETREASURY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: etreasury

command: 
  - "bin/sh" 
  - "-c"
  - |
    curl -X POST --location "${ETREASURY_HOST}etreasury/payment/v1/_processReconciliationV3" \
    --header 'Content-Type: application/json' \
    --data '{
        "authToken": "e231def1-fa70-4fff-93be-4a0490f66ccb",
        "userInfo": {
            "id": 483,
            "uuid": "ee6d94ef-f029-4b8a-8560-5b001d809b20",
            "userName": "payment-collector",
            "name": "payment-collector",
            "mobileNumber": "1002335566",
            "emailId": null,
            "locale": null,
            "type": "EMPLOYEE",
            "roles": [
                {
                    "name": "FSO_ROLE",
                    "code": "FSO_ROLE",
                    "tenantId": "kl"
                },
                {
                    "name": "CASE_VIEWER",
                    "code": "CASE_VIEWER",
                    "tenantId": "kl"
                },
                {
                    "name": "Citizen",
                    "code": "CITIZEN",
                    "tenantId": "kl"
                },
                {
                    "name": "PAYMENT_COLLECTOR",
                    "code": "PAYMENT_COLLECTOR",
                    "tenantId": "kl"
                },
                {
                    "name": "CASE_REVIEWER",
                    "code": "CASE_REVIEWER",
                    "tenantId": "kl"
                },
                {
                    "name": "CASE_EDITOR",
                    "code": "CASE_EDITOR",
                    "tenantId": "kl"
                },
                {
                    "name": "Employee",
                    "code": "EMPLOYEE",
                    "tenantId": "kl"
                }
            ],
            "active": true,
            "tenantId": "kl",
            "permanentCity": null
        },
        "msgId": "1780911676981|en_IN",
        "apiId": "Dristi"
    }'