templates:
  default: &default
    chart: ../charts/{{ requiredEnv "SERVICE_GROUP" }}/{{`{{ .Release.Name }}`}}
    version: 0.1.0
    namespace: egov
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    values:
      - ../charts/environments/{{ requiredEnv "HELMFILE_ENV" }}.yaml
    # secrets:
    #   - ../charts/environments/{{ requiredEnv "HELMFILE_ENV" }}-secrets.yaml
commonLabels:
  deployment: "pucar"

releases:
  - name: {{ requiredEnv "SERVICE_NAME" }}
    installed: true
    <<: *default
