apiVersion: v1
kind: ServiceAccount
metadata:
  name: egov-cluster-developer-sa
  namespace: egov
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egov-cluster-developer-role
rules:
- apiGroups: ["", "apps", "networking.k8s.io"]
  resources: 
    - deployments
    - deployments/rollback
    - deployments/scale
    - deployments/status
    - ingresses
    - services
    - pods
    - pods/log
    - pods/portforward
    - configmaps
    - secrets
    - namespaces
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: egov-cluster-developer-crb
subjects:
- kind: ServiceAccount
  name: egov-cluster-developer-sa
  namespace: egov
roleRef:
  kind: ClusterRole
  name: egov-cluster-developer-role
  apiGroup: rbac.authorization.k8s.io
