apiVersion: v1
kind: Secret
metadata:
  name: egov-cluster-developer-token
  namespace: egov
  annotations:
    kubernetes.io/service-account.name: egov-cluster-developer-sa
type: kubernetes.io/service-account-token
