# Common Labels
labels:
  app: "case-status-cron"
  group: "cronjobs"

# Cron schedule
cron:
  schedule: "0 18 * * *"
  timezone: "Asia/Kolkata"

# Container Configs
image:
  repository: "docker.io/venkatramireddyb/cronjob"
  tag: "v1"

# Environment variables sourced from ConfigMap
env: |
  - name: CASE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: case

command:
  - "bin/sh"
  - "-c"
  - |
    curl -X POST --location "${CASE_HOST}case/v1/_runCronJob"